apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_NAME: {{ .Release.Name | quote }}
  COMMIT: {{ .Values.commit | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  PROJECT: {{ .Values.project }}
  REVISION: {{ .Release.Revision | quote }}
